const quotes = [
  "Czyż może niewiasta zapomnieć o swym niemowlęciu, ta która kocha syna swego łona? A nawet gdyby ona zapomniała, Ja nie zapomnę o tobie. Oto wyryłem cię na obu dłoniach (Iz 49, 15-16)",
  "Jezus zaraz przemówił do nich: «Odwagi! Ja jestem, nie bójcie się!» (Mt 14, 27)",
  "Lecz na widok silnego wiatru uląkł się i gdy zaczął tonąć, krzyknął: «Panie, ratuj mnie!» Jezus natychmiast wyciągnął rękę i chwycił go, mówiąc: «Czemu zwątpiłeś, małej wiary?» (Mt 14, 30-31)",
  "Zróbcie wszystko, cokolwiek wam powie (J 2,5).",
  "Powierz Panu swoją drogę i zaufaj Mu: On sam będzie działał (Ps 37, 5)",
  "Nadeszła [tam] kobieta z Samarii, aby zaczerpnąć wody. Jezus rzekł do niej: «Daj Mi pić!» (J 4,7)",
  "A dla was, czczących moje imię, wzejdzie słońce sprawiedliwości i uzdrowienie w jego skrzydłach. Wyjdziecie [swobodnie] i będziecie podskakiwać jak tuczone cielęta (Ml 3, 20)",
  "Niewiasto, Oto Syn Twój (…), Oto Matka Twoja (J 19, 26-27)",
  "(…) bo człowiek patrzy na to, co widoczne dla oczu, Pan natomiast patrzy na serce (1 Sm 16, 7)",
  "Czyż ci nie rozkazałem: Bądź mężny i mocny? Nie bój się i nie lękaj, ponieważ z tobą jest Pan, Bóg twój, wszędzie, gdziekolwiek pójdziesz (Joz 1, 9)",
  "Nie porzucaj starego przyjaciela. Nowy z nim nie jest na równi. Przyjaciel nowy jest jak nowe wino, gdy się zestarzeje, z przyjemnością je wypijesz (Syr 9, 10)",
  "Wierny przyjaciel jest lekarstwem życia (Syr 6, 17)",
  "Połóż mnie jak pieczęć na twoim sercu, jak pieczęć na twoim ramieniu, bo jak śmierć potężna jest miłość (…), żar jej to żar ognia, uderzenie boskiego gromu (Pnp 8, 6)",
  "Wszystkie troski wasze przerzućcie na Niego, gdyż Jemu zależy na was (1 P 5, 7)",
  "Miłość nie zna lęku. Doskonała miłość usuwa lęk (1 Jn 4, 18)",
  "Dla mnie bowiem żyć - to Chrystus, a umrzeć - to zysk (Flp 1, 21)",
  "Będziesz prześliczną koroną w rękach Pana, królewskim diademem w dłoni twego Boga (Iz 62,3)",
  "Nie lękaj się ich, bo jestem z tobą, by cię chronić - wyrocznia Pana (Jr 1, 8)",
  "«Nagi wyszedłem z łona matki i nagi tam wrócę. Dał Pan i zabrał Pan. Niech będzie imię Pańskie błogosławione!» (Hi 1, 20)",
  "Pan jest moim pasterzem, nie brak mi niczego. &lt;…&gt; Orzeźwia moją duszę. Wiedzie mnie po właściwych ścieżkach przez wzgląd na swoje imię. Chociażbym chodził ciemną doliną, zła się nie ulęknę, bo Ty jesteś ze mną (Ps 23, 1.3-4)",
  "Tak, dobroć i łaska pójdą w ślad za mną przez wszystkie dni mego życia i zamieszkam w domu Pańskim po najdłuższe czasy (Ps 23,6)",
  "Tobie mnie poruczono przed urodzeniem, Ty jesteś moim Bogiem od łona mojej matki (Ps 22,11)",
  "Daj mi poznać drogi Twoje, Panie, i naucz mnie Twoich ścieżek! Prowadź mnie według Twej prawdy i pouczaj, bo Ty jesteś Bóg, mój Zbawca, i w Tobie mam zawsze nadzieję (Ps 25, 4-5)",
  "Panie, przenikasz i znasz mnie, Ty wiesz, kiedy siadam i wstaję. Z daleka przenikasz moje zamysły (Ps 139, 1-2)",
  "Nie lękaj się, bo Ja jestem z tobą; nie trwóż się, bom Ja twoim Bogiem. Umacniam cię, jeszcze i wspomagam, podtrzymuję cię moją prawicą sprawiedliwą (Iz 41,10)",
  "Nie lękaj się, bo cię wykupiłem, wezwałem cię po imieniu; tyś moim! Gdy pójdziesz przez wody, Ja będę z tobą i gdy przez rzeki, nie zatopią ciebie. Gdy pójdziesz przez ogień, nie spalisz się i nie strawi cię płomień. Albowiem Ja jestem Pan, twój Bóg, Święty Izraela, twój Zbawca (Iz 43, 1-3)",
  "Ponieważ drogi jesteś w moich oczach, nabrałeś wartości i Ja cię miłuję, przeto daję ludzi za ciebie i narody za życie twoje. Nie lękaj się, bo jestem z tobą (Iz 43, 4-5)",
  "Nie wspominajcie wydarzeń minionych, nie roztrząsajcie w myśli dawnych rzeczy. Oto Ja dokonuję rzeczy nowej (Iz 43, 18-19)",
  "Bo mam przed oczyma Twoją łaskawość i postępuję w Twej prawdzie (Ps 26, 3)",
  "Okryje cię swymi piórami i schronisz się pod Jego skrzydła: Jego wierność to puklerz i tarcza (Ps 91, 4)",
  "Wy zatem, bracia, powołani zostaliście do wolności. Tylko nie bierzcie tej wolności jako zachęty do hołdowania ciału, wręcz przeciwnie, miłością ożywieni służcie sobie wzajemnie! (Ga 5, 13)",
];

export default quotes;
